AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an EC2 security group in the provided VPC
Parameters:
  GroupDescription:
    Type: String
    Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#cfn-ec2-securitygroup-groupdescription
  GroupName:
    Type: String
    Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#cfn-ec2-securitygroup-groupname
  VpcId:
    Type: String
    Description: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#cfn-ec2-securitygroup-vpcid
Resources:
  Resource:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref 'GroupDescription'
      GroupName: !Ref 'GroupName'
      VpcId: !Ref 'VpcId'
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/24
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 10.0.0.0/24
          
Outputs:
  GroupId:
    Value: !Ref Resource
  VpcId:
    Value: !Ref 'VpcId'
